### ISSUE TITLE
sendAsync only supports objects as payloads but gets called with an array

### ISSUE THREAD

**Issue by bumi** [floating/ethereum-provider#2]
I am trying to use eth-provider in combination with truffle (a truffle 4.x project). While trying to run a deployment script I am getting an `TypeError: this._send(...).then is not a function` error

I tried to debug that error and it seems that the [sendAsync function](https://github.com/floating/ethereum-provider/blob/master/index.js#L106) is somehow called with an array as payload. But only a object is expected as param. 
payload:
```
[ { jsonrpc: '2.0',
    id: 6,
    method: 'eth_getFilterChanges',
    params: [ '0x30a6dd9fd08ef418a2c9a932a51710a2' ] } ]
```

### Trace 

```
/home/bumi/src/kredits/truffle-kredits/node_modules/ethereum-provider/index.js:106
    return this._send(payload.method, payload.params).then(result => {
                                                      ^
TypeError: this._send(...).then is not a function
    at EthereumProvider.sendAsync (/home/bumi/src/kredits/truffle-kredits/node_modules/ethereum-provider/index.js:108:55)
    at EthereumProvider.sendAsync (/home/bumi/src/kredits/truffle-kredits/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:128:1)
    at Provider.sendAsync (/home/bumi/src/kredits/truffle-kredits/node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:24:1)
    at RequestManager.poll (/home/bumi/src/kredits/truffle-kredits/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:230:1)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
```

### Versions
"eth-provider": {
  "version": "0.2.1"
» truffle version
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
» node --version
v11.9.0

**Comment by floating** [comment]
Hey @bumi!

eth-provider's `sendAsync` follows EIP-1193's backwards compatibility outlined here: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#web3js-backwards-compatibility which does not handle arrays of requests, but it's possible that it should. Do you know where this batch request is being created?

**Comment by bumi** [comment]
hmm, that's interesting. 
Sadly so far I couldn't figure that out what exactly initiates that `eth_getFilterChanges` call... it's super complicated with all those truffle and web3 dependencies. The only stack trace I got was the one mentioned above.
I tried to deploy a contract through truffle, but eth-provider configured as web3 provider. 

But I have seen that web3-provider-engine supports an array as payload: https://github.com/MetaMask/web3-provider-engine/blob/a17a32fab2717e5c6d600c5a8c25f9591c085aff/index.js#L112

**Comment by bumi** [comment]
and there is some kind of batch requests that use arrays: 

https://github.com/ethereum/web3.js/blob/v0.20.6/lib/web3/requestmanager.js#L105
=> payload generate from: 
https://github.com/ethereum/web3.js/blob/v0.20.6/lib/web3/jsonrpc.js#L72-L83

**Comment by bumi** [comment]
even though everything changed in web3.js v1 there is seems to be still some batch calls.
https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/src/providers/HttpProvider.js#L113
though providers implement it differently, e.g. https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/src/providers/Web3EthereumProvider.js#L157


would you accept a PR that adds support for calls with an array?

**Comment by floating** [comment]
Yes, I would accept it. If we're going to provide the backwards compatibility of `sendAsync` then it should cover handling this case.
